/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as _01BasicMathSol from "./01_BasicMath.sol";
export type { _01BasicMathSol };
import type * as _02ControlStructuresSol from "./02_ControlStructures.sol";
export type { _02ControlStructuresSol };
import type * as _03EmployeeStorageSol from "./03_EmployeeStorage.sol";
export type { _03EmployeeStorageSol };
import type * as _04ArraysExerciseSol from "./04_ArraysExercise.sol";
export type { _04ArraysExerciseSol };
import type * as _05FavoriteRecordsSol from "./05_FavoriteRecords.sol";
export type { _05FavoriteRecordsSol };
import type * as _06GarageManagerSol from "./06_GarageManager.sol";
export type { _06GarageManagerSol };
import type * as _07InheritanceSol from "./07_Inheritance.sol";
export type { _07InheritanceSol };
import type * as _08ImportsExerciseSol from "./08_ImportsExercise.sol";
export type { _08ImportsExerciseSol };
import type * as _09ErrorTriageExerciseSol from "./09_ErrorTriageExercise.sol";
export type { _09ErrorTriageExerciseSol };
import type * as _10NewExerciseSol from "./10_NewExercise.sol";
export type { _10NewExerciseSol };
import type * as _11UnburnableTokenSol from "./11_UnburnableToken.sol";
export type { _11UnburnableTokenSol };
import type * as _12WeightedVotingSol from "./12_WeightedVoting.sol";
export type { _12WeightedVotingSol };
import type * as _13HaikuNftSol from "./13_HaikuNFT.sol";
export type { _13HaikuNftSol };
export type { Lock } from "./Lock";
