/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BasicMathInterface extends Interface {
  getFunction(nameOrSignature: "adder" | "subtractor"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "adder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subtractor",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "adder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subtractor", data: BytesLike): Result;
}

export interface BasicMath extends BaseContract {
  connect(runner?: ContractRunner | null): BasicMath;
  waitForDeployment(): Promise<this>;

  interface: BasicMathInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adder: TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, boolean] & { sum: bigint; error: boolean }],
    "view"
  >;

  subtractor: TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, boolean] & { difference: bigint; error: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adder"
  ): TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, boolean] & { sum: bigint; error: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "subtractor"
  ): TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, boolean] & { difference: bigint; error: boolean }],
    "view"
  >;

  filters: {};
}
