/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Employee,
  EmployeeInterface,
} from "../../../contracts/07_Inheritance.sol/Employee";

const _abi = [
  {
    inputs: [],
    name: "getAnnualCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "idNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managerId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Employee__factory {
  static readonly abi = _abi;
  static createInterface(): EmployeeInterface {
    return new Interface(_abi) as EmployeeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Employee {
    return new Contract(address, _abi, runner) as unknown as Employee;
  }
}
