/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddressBook__factory } from "./AddressBook__factory";
export { AddressBookFactory__factory } from "./AddressBookFactory__factory";
