/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Salaried,
  SalariedInterface,
} from "../../../contracts/07_Inheritance.sol/Salaried";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_idNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_managerId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_annualSalary",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "annualSalary",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAnnualCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "idNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managerId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161012e38038061012e83398101604081905261002f91610040565b60009290925560015560025561006e565b60008060006060848603121561005557600080fd5b8351925060208401519150604084015190509250925092565b60b28061007c6000396000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80633f83ea3b14604b57806350dca6ab1460655780635cdee0c014606d578063f5895a0a146074575b600080fd5b605360005481565b60405190815260200160405180910390f35b605360025481565b6002546053565b60536001548156fea2646970667358221220c8c86bd19306ab6779a7d35dd164f23212040827a6cda3d10cca2e2c16b53d9c64736f6c63430008140033";

type SalariedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SalariedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Salaried__factory extends ContractFactory {
  constructor(...args: SalariedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _idNumber: BigNumberish,
    _managerId: BigNumberish,
    _annualSalary: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _idNumber,
      _managerId,
      _annualSalary,
      overrides || {}
    );
  }
  override deploy(
    _idNumber: BigNumberish,
    _managerId: BigNumberish,
    _annualSalary: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _idNumber,
      _managerId,
      _annualSalary,
      overrides || {}
    ) as Promise<
      Salaried & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Salaried__factory {
    return super.connect(runner) as Salaried__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SalariedInterface {
    return new Interface(_abi) as SalariedInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Salaried {
    return new Contract(address, _abi, runner) as unknown as Salaried;
  }
}
