/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Salesperson,
  SalespersonInterface,
} from "../../../contracts/07_Inheritance.sol/Salesperson";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_idNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_managerId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_hourlyRate",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getAnnualCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hourlyRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "idNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managerId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161018638038061018683398101604081905261002f91610040565b60009290925560015560025561006e565b60008060006060848603121561005557600080fd5b8351925060208401519150604084015190509250925092565b6101098061007d6000396000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80633f83ea3b14604b57806359a7b3fe1460655780635cdee0c014606d578063f5895a0a146073575b600080fd5b605360005481565b60405190815260200160405180910390f35b605360025481565b6053607b565b605360015481565b6000600254610820608b91906090565b905090565b808202811582820484141760cd577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b9291505056fea2646970667358221220d019995862d83b99440f62cef4f8500666ead880c1eff5bf485f4d7fe58d870664736f6c63430008140033";

type SalespersonConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SalespersonConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Salesperson__factory extends ContractFactory {
  constructor(...args: SalespersonConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _idNumber: BigNumberish,
    _managerId: BigNumberish,
    _hourlyRate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _idNumber,
      _managerId,
      _hourlyRate,
      overrides || {}
    );
  }
  override deploy(
    _idNumber: BigNumberish,
    _managerId: BigNumberish,
    _hourlyRate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _idNumber,
      _managerId,
      _hourlyRate,
      overrides || {}
    ) as Promise<
      Salesperson & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Salesperson__factory {
    return super.connect(runner) as Salesperson__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SalespersonInterface {
    return new Interface(_abi) as SalespersonInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Salesperson {
    return new Contract(address, _abi, runner) as unknown as Salesperson;
  }
}
