/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EmployeeInterface extends Interface {
  getFunction(
    nameOrSignature: "getAnnualCost" | "idNumber" | "managerId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAnnualCost",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "idNumber", values?: undefined): string;
  encodeFunctionData(functionFragment: "managerId", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getAnnualCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idNumber", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "managerId", data: BytesLike): Result;
}

export interface Employee extends BaseContract {
  connect(runner?: ContractRunner | null): Employee;
  waitForDeployment(): Promise<this>;

  interface: EmployeeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAnnualCost: TypedContractMethod<[], [bigint], "view">;

  idNumber: TypedContractMethod<[], [bigint], "view">;

  managerId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAnnualCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "idNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "managerId"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
