/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ControlStructuresInterface extends Interface {
  getFunction(nameOrSignature: "doNotDisturb" | "fizzBuzz"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "doNotDisturb",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fizzBuzz",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "doNotDisturb",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fizzBuzz", data: BytesLike): Result;
}

export interface ControlStructures extends BaseContract {
  connect(runner?: ContractRunner | null): ControlStructures;
  waitForDeployment(): Promise<this>;

  interface: ControlStructuresInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doNotDisturb: TypedContractMethod<[_time: BigNumberish], [string], "view">;

  fizzBuzz: TypedContractMethod<[_number: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doNotDisturb"
  ): TypedContractMethod<[_time: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "fizzBuzz"
  ): TypedContractMethod<[_number: BigNumberish], [string], "view">;

  filters: {};
}
