/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressBook } from "./AddressBook";
export type { AddressBookFactory } from "./AddressBookFactory";
