/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EngineeringManager } from "./EngineeringManager";
export type { Hourly } from "./Hourly";
export type { InheritanceSubmission } from "./InheritanceSubmission";
export type { Manager } from "./Manager";
export type { Salaried } from "./Salaried";
export type { Salesperson } from "./Salesperson";
export type { Employee } from "./Employee";
