/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "addReport" | "employeeIds" | "resetReports"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employeeIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetReports",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addReport", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "employeeIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetReports",
    data: BytesLike
  ): Result;
}

export interface Manager extends BaseContract {
  connect(runner?: ContractRunner | null): Manager;
  waitForDeployment(): Promise<this>;

  interface: ManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReport: TypedContractMethod<
    [_employeeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  employeeIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  resetReports: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReport"
  ): TypedContractMethod<[_employeeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "employeeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resetReports"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
